### ISSUE TITLE
New Aggregator Checklist

### ISSUE THREAD

**Issue by jiguantong** [ringecosystem/xapi-offchain#23]
- [ ] Deploy and config
   - [ ] deploy
   - [ ] add_data_source
   - [ ] set_publish_chain_config
   - [ ] Deposit 10 NEAR for storage fee
- [ ] Deposit tx fee for exAggregator address
- [ ] Update the near index if the new aggregator account is not included in the wildcard list
